# -*- coding: utf-8 -*-
"""guessthenumber

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/188kXbIClNCSR345E-oecF6Tt0LD5zFxp
"""

import math
import random

print('__________GUESS THE NUMBER__________')
try:
  lower = int(input("enter the lower key... "))
  upper = int(input("enter the upper key... "))
except ValueError:
  print('Invalid!! You can only choose number...')

number = random.randint(lower,upper)

print('\n You have only', 
      round(math.log(upper - lower + 1,2)), 
      'to guess the number!!! \n')

count = 0
while count < math.log(upper-lower + 1,2):
  count += 1
  try:
    guess = int(input("Guesss a number - "))
  except ValueError:
    print('ooops!!! You can only guess numbers')

  if number == guess:
    print("congratulations! you did in ", count, 'try')
    break

  elif number > guess:
    print('You have guess too low!')

  elif number < guess:
    print('You have guess too high!')

if count >= math.log(upper - lower + 1, 2):
  print("Try again!!!")
  print(' The correct number is %d' %number)